spring:
  datasource:
    #url: jdbc:h2:tcp://localhost/~/post
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none #Application 실행 시점에 Entity 삭제 & 재생성
    properties:
      hibernate:
        show_sql: true #생성한 SQL 이 다 보임 :) System out 을 통해 출력.
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #sql 을 전부 DEBUG 모드로 남긴다는 뜻. Logger 를 통해.
    org.hibernate.orm.jdbc.bind: trace

server:
  address: 0.0.0.0
  port: 8080

